### PR TITLE
validate zip codes

### PR DESCRIPTION
**Pull request by danielruss**
@anthonypetersen @JoeArmani   if you have not already see long winded comment in [#345.  ](https://github.com/episphere/questionnaire/issues/345#issuecomment-2284680417).  We really could push now, but if we could get a translation to fix the i18n.js. That would be better.

### CODE REVIEW

**Comment by danielruss** [comment]
ok. I have ants in my pants and could not wait.  I addeed the translate.  We just need the spanish translation for validationZipCode in es.js

**Review by JoeArmani — APPROVED** [review]

**Review by anthonypetersen — APPROVED** [review]
looks good, I'll check in with Deanna about a translation

**Comment by danielruss** [comment]
Do you want it pushed to main to fix the "english-only" zip code formatting?

**Comment by danielruss** [comment]
actually, only dev get the newest version, you have to set the version in prod/stage.
so I'll push.

**Comment by anthonypetersen** [comment]
Will have another PR once translations come back

**Pull request merged**
