### PR TITLE
Issue#347

### PR DESCRIPTION
**Pull request by iqbal-singh**

### CODE REVIEW

**Comment by guinevere83** [comment]
At least testing module 4, the way I have been seeing things is that the check and text boxes only clear if AGE is defined and do not if it is not. I'm not sure if we have an example of a question without a verifier to check against. I'm curious to see how things would work with a question where the text box doesn't have a verifier.

**Comment by guinevere83** [comment]
To elaborate, the checkbox and textbox behavior works as expected if there are no defined verifiers. I'm not sure how useful a use case this is but if I defined AGE as NR, the textbox behavior does not work as expected. This particular issue might have trouble for certain variables that are left NR, although I'm not sure where we might have questions where that comes into play.

**Comment by danielruss** [comment]
This is an old pull request  not an issue.  If this relates to issue #347 Check to see if it falls under #376.  if it does not, create a new issue.

**Comment by guinevere83** [comment]
We can close this issue and start a new one.

**Pull request merged**
