### PR TITLE
issue #448 fix

### PR DESCRIPTION
**Pull request by danielruss**
Fix Null pointer error in modal. And bootstrap 4/5 issue closing Modal.

### CODE REVIEW

**Comment by anthonypetersen** [comment]
@danielruss I already have a fix going in for this with my current PR

**Comment by anthonypetersen** [comment]
@JoeArmani @danielruss more of an FYI but comment if I'm wrong... with these modals I don't think we want to have `data-dismiss` and `data-bs-dismiss` both in the attributes section, it's not best practice from what I understand since we aren't falling back to BS4

**Comment by danielruss** [comment]
The spanish implementation PR?

**Comment by danielruss** [comment]
I think the PWA uses BS4.

**Comment by anthonypetersen** [comment]
> The spanish implementation PR?

yes - good point on the PWA comment though, I'll add back in the BS4 attribute

**Pull request closed without merging**
